#!/usr/bin/env python3
"""Render a Qwen3.8-27B Compose overlay for a given GPU topology.

The serving topology is (number of engines) x (tensor-parallel size). Both are
derived from how many GPUs you have and how you want them split, so this
replaces a family of near-identical hand-written overlays with one generator.

    render_topology.py --gpus 4 --tensor-parallel 2      # 2 engines, 2 GPUs each
    render_topology.py --gpus 1 --tensor-parallel 1      # 1 engine, 1 GPU
    render_topology.py --gpus 8 --tensor-parallel 2 -o topology.8gpu-tp2.yaml

Rendered overlays are applied on top of the base file:

    docker compose -f docker-compose.yaml -f <overlay> up -d

Which split to pick is a measured question, not a matter of taste; see
docs/models.md. The short version for this model is that more engines of a
smaller tensor-parallel size usually beat fewer, larger ones, because engines
partition the prefix cache and tensor parallelism costs an allreduce per layer.
The floor is set by whether the weights fit.
"""

import argparse
import json
import pathlib
import sys

# Qwen3.8-27B-FP8 weights, rounded up from the 27.78GB of safetensors. Used
# only to warn about topologies that cannot fit; it is not a hard limit because
# activation and KV headroom depend on max-model-len and batch size.
WEIGHT_GIB = 28

# Headroom multiplier over raw weight share. Below this there is no room for
# KV cache, activations, or CUDA graphs, so the engine either fails to start or
# starts with a KV pool too small to be useful.
MIN_HEADROOM = 1.4

BANNER = """# GENERATED by render_topology.py -- do not edit by hand.
#
# Topology: {engines} engine(s) x TP{tp} across {gpus} GPU(s).
# Regenerate with:
#   ./render_topology.py --gpus {gpus} --tensor-parallel {tp}
#
# Apply on top of the base file:
#   docker compose -f docker-compose.yaml -f {name} up -d
#
# Each GPU holds about {per_gpu:.1f}GiB of weights, so this needs a card with at
# least roughly {min_vram:.0f}GiB to leave room for KV cache and activations.
"""


def topology_plan(gpus, tp):
    """Returns the full topology as data, independent of any YAML rendering.

    Callers and tests inspect this rather than re-parsing the rendered file,
    which keeps the repository free of a YAML parser dependency; the existing
    Compose validators avoid one for the same reason.
    """

    engines = gpus // tp
    per_gpu = WEIGHT_GIB / tp
    return {
        "gpus": gpus,
        "tensor_parallel": tp,
        "engines": engines,
        "weights_gib_per_gpu": round(per_gpu, 2),
        "min_vram_gib_per_gpu": round(per_gpu * MIN_HEADROOM, 1),
        "placement": [
            {
                "name": f"qwen38-e{index}",
                "gpu_ids": list(range(index * tp, (index + 1) * tp)),
                "port": 8020 + index,
            }
            for index in range(engines)
        ],
    }


def validate_topology(gpus, tp):
    """Raises ValueError for a topology this model or vLLM cannot serve."""

    if gpus < 1:
        raise ValueError("--gpus must be at least 1")
    if tp < 1 or tp > gpus:
        raise ValueError("--tensor-parallel must be between 1 and --gpus")
    if gpus % tp:
        raise ValueError(f"--gpus {gpus} is not divisible by --tensor-parallel {tp}")
    # vLLM shards attention heads across the tensor-parallel group, which
    # requires a power of two for this model's head counts.
    if tp & (tp - 1):
        raise ValueError(f"--tensor-parallel {tp} must be a power of two")


def engine_service(index, gpu_ids, tp, port, numa):
    """Renders one engine service block."""

    devices = ", ".join(f'"{gpu}"' for gpu in gpu_ids)
    cpuset = f'\n    cpuset: "{numa}"' if numa else ""
    return f"""  qwen38-e{index}:
    image: ${{IMAGE:-voipmonitor/vllm:gilded-gnosis-v20-vllm4d006a4-b12xcd3ce19-fi1ac6942-cu132-20260810-r34}}
    container_name: qwen38-e{index}
    entrypoint: ["/opt/venv/bin/vllm", "serve", "/workspace/model"]
    restart: unless-stopped
    ipc: host
    init: true
    shm_size: {8 * tp}gb{cpuset}
    ulimits:
      memlock: -1
      stack: 67108864
      nofile: {{soft: 1048576, hard: 1048576}}
    ports:
      - "127.0.0.1:{port}:8000"
    volumes:
      - ${{QWEN_MODEL_DIR:-/prod/models/Qwen/Qwen3.8-27B-FP8}}:/workspace/model:ro
      - ${{ENGINE_CACHE_DIR:-/prod/engine-cache}}:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [{devices}]
              capabilities: [gpu]
    environment:
      CUDA_DEVICE_ORDER: PCI_BUS_ID
      NCCL_P2P_DISABLE: ${{NCCL_P2P_DISABLE:-0}}
      VLLM_API_KEY: ${{VLLM_API_KEY:-qwen-local}}
    command:
      - --served-model-name=${{SERVED_MODEL_NAME:-qwen3.8-27b}}
      - --host=0.0.0.0
      - --port=8000
      - --tensor-parallel-size={tp}
      - --max-model-len=${{MAX_MODEL_LEN:-262144}}
      - --max-num-seqs=${{MAX_NUM_SEQS:-256}}
      - --gpu-memory-utilization=${{GPU_MEMORY_UTILIZATION:-0.90}}
      - --enable-prefix-caching
      - --reasoning-parser=qwen3
      - --tool-call-parser=${{TOOL_CALL_PARSER:-qwen3_xml}}
      - --enable-auto-tool-choice
      - --limit-mm-per-prompt={{"image":${{MM_IMAGE_LIMIT:-4}},"video":${{MM_VIDEO_LIMIT:-1}}}}
      - --kv-events-config={{"enable_kv_cache_events":true,"publisher":"zmq","endpoint":"tcp://*:5557","replay_endpoint":"tcp://*:5558","buffer_steps":10000,"hwm":100000,"max_queue_size":100000,"topic":""}}
      - --override-generation-config={{"top_p":0.95}}
      - --speculative-config={{"method":"mtp","num_speculative_tokens":${{NUM_SPECULATIVE_TOKENS:-2}}}}
"""


def render(gpus, tp, numa_split, name):
    """Renders the full overlay text for a topology."""

    engines = gpus // tp
    per_gpu = WEIGHT_GIB / tp
    upstreams = ",".join(f"http://qwen38-e{i}:8000" for i in range(engines))
    live = ",".join(f"tcp://qwen38-e{i}:5557" for i in range(engines))
    replay = ",".join(f"tcp://qwen38-e{i}:5558" for i in range(engines))

    out = [BANNER.format(
        engines=engines, tp=tp, gpus=gpus, name=name,
        per_gpu=per_gpu, min_vram=per_gpu * MIN_HEADROOM,
    )]
    out.append("services:")
    out.append("  ds4-loadbalancer:")
    out.append("    environment:")
    out.append(f"      MD_UPSTREAM: ${{MD_UPSTREAM:-{upstreams}}}")
    out.append(f"      MD_KV_EVENT_LIVE_ENDPOINTS: ${{MD_KV_EVENT_LIVE_ENDPOINTS:-{live}}}")
    out.append(f"      MD_KV_EVENT_REPLAY_ENDPOINTS: ${{MD_KV_EVENT_REPLAY_ENDPOINTS:-{replay}}}")
    out.append("  # The base file's fixed pair is parked so a stale container cannot")
    out.append("  # hold GPUs while this topology starts.")
    out.append('  qwen38-a:\n    profiles: ["base-pair-only"]')
    out.append('  qwen38-b:\n    profiles: ["base-pair-only"]')
    for engine in topology_plan(gpus, tp)["placement"]:
        index, gpu_ids = int(engine["name"].rsplit("e", 1)[1]), engine["gpu_ids"]
        # Keep an engine's GPUs on one NUMA node where the split is known.
        numa = ""
        if numa_split:
            half = gpus // 2
            numa = numa_split[0] if gpu_ids[-1] < half else numa_split[1]
        out.append(engine_service(index, gpu_ids, tp, engine["port"], numa))
    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--gpus", type=int, required=True)
    parser.add_argument("--tensor-parallel", type=int, required=True)
    parser.add_argument("--output", "-o", type=pathlib.Path)
    parser.add_argument(
        "--numa-split", default="",
        help="comma-separated cpusets for the low and high GPU halves, "
             "e.g. '0-11,24-35;12-23,36-47'. Omit on single-socket hosts.",
    )
    parser.add_argument("--json", action="store_true", help="print the plan and exit")
    args = parser.parse_args()

    gpus, tp = args.gpus, args.tensor_parallel
    try:
        validate_topology(gpus, tp)
    except ValueError as error:
        raise SystemExit(str(error)) from error

    plan = topology_plan(gpus, tp)
    if args.json:
        print(json.dumps(plan, indent=2))
        return 0

    name = args.output.name if args.output else f"topology.{gpus}gpu-tp{tp}.yaml"
    numa = args.numa_split.split(";") if args.numa_split else None
    if numa and len(numa) != 2:
        raise SystemExit("--numa-split needs exactly two semicolon-separated cpusets")
    text = render(gpus, tp, numa, name)

    if args.output:
        args.output.write_text(text)
        print(json.dumps(plan))
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
