import os
import pathlib
import subprocess
import tempfile
import unittest


ROOT = pathlib.Path(__file__).resolve().parents[1]
PLANNER = ROOT / "bench" / "drone_release_plan.sh"
GUARD = ROOT / "bench" / "drone_release_guard.sh"
PUBLISH = ROOT / "bench" / "drone_release_publish.sh"


class DroneReleaseTest(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.root = pathlib.Path(self.temporary.name)
        subprocess.run(["git", "init", "-q", "-b", "main"], cwd=self.root, check=True)
        subprocess.run(
            ["git", "config", "user.email", "ci@example.invalid"],
            cwd=self.root,
            check=True,
        )
        subprocess.run(
            ["git", "config", "user.name", "CI test"], cwd=self.root, check=True
        )
        self.fake_bin = self.root / "fake-bin"
        self.fake_bin.mkdir()
        cargo = self.fake_bin / "cargo"
        cargo.write_text(
            "#!/bin/sh\n"
            "[ \"${1-}\" = pkgid ] || exit 1\n"
            "version=$(sed -n 's/^version = \"\\(.*\\)\"$/\\1/p' Cargo.toml | head -1)\n"
            "[ -n \"$version\" ] || exit 1\n"
            "printf 'path+file:///fixture#release-fixture@%s\\n' \"$version\"\n"
        )
        cargo.chmod(0o755)
        self.write_manifest("1.2.0-alpha.1")
        self.commit()

    def tearDown(self):
        self.temporary.cleanup()

    def write_manifest(self, version):
        (self.root / "src").mkdir(exist_ok=True)
        (self.root / "src" / "lib.rs").write_text("")
        (self.root / "Cargo.toml").write_text(
            "[package]\n"
            'name = "release-fixture"\n'
            f'version = "{version}"\n'
            'edition = "2024"\n'
        )
        (self.root / "Cargo.lock").write_text(
            "# This file is automatically @generated by Cargo.\n"
            "# It is not intended for manual editing.\n"
            "version = 4\n\n"
            "[[package]]\n"
            'name = "release-fixture"\n'
            f'version = "{version}"\n'
        )

    def commit(self):
        subprocess.run(["git", "add", "-A"], cwd=self.root, check=True)
        subprocess.run(["git", "commit", "-qm", "fixture"], cwd=self.root, check=True)
        return subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=self.root,
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip()

    def environment(self, **overrides):
        sha = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=self.root,
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip()
        environment = os.environ.copy()
        environment["PATH"] = f"{self.fake_bin}:{environment['PATH']}"
        environment.update(
            {
                "DRONE_BUILD_EVENT": "tag",
                "DRONE_TAG": "v1.2.0-alpha.1",
                "DRONE_COMMIT_REF": "refs/tags/v1.2.0-alpha.1",
                "DRONE_COMMIT_SHA": sha,
            }
        )
        environment.update(overrides)
        return environment

    def run_script(self, script, *arguments, environment=None):
        return subprocess.run(
            ["sh", str(script), *arguments],
            cwd=self.root,
            env=environment or self.environment(),
            check=False,
            capture_output=True,
            text=True,
        )

    def install_fake_crane(self):
        sha = self.environment()["DRONE_COMMIT_SHA"]
        crane = self.fake_bin / "crane"
        crane.write_text(
            "#!/bin/sh\n"
            "printf '%s\\n' \"$*\" >> crane-calls\n"
            "case \"${1-}\" in\n"
            "  auth) exit 0 ;;\n"
            "  config) printf '%s\\n' '{\"config\":{\"Labels\":{"
            f"\"org.opencontainers.image.source\":\"https://github.com/helixml/mini-dynamo\","
            f"\"org.opencontainers.image.version\":\"1.2.0-alpha.1\","
            f"\"org.opencontainers.image.revision\":\"{sha}\"}}}}' ;;\n"
            "  digest)\n"
            "    case \"$2\" in\n"
            "      *:rust-*|*:companion-rust-*) printf '%s\\n' sha256:fixture ;;\n"
            "      *:companion-*) marker=companion-copied ;;\n"
            "      *) marker=lb-copied ;;\n"
            "    esac\n"
            "    if [ -z \"${marker-}\" ]; then exit 0; fi\n"
            "    if [ -f \"$marker\" ]; then printf '%s\\n' sha256:fixture; exit 0; fi\n"
            "    case \"${FAKE_DESTINATION_STATE-missing}\" in\n"
            "      same) printf '%s\\n' sha256:fixture ;;\n"
            "      different) printf '%s\\n' sha256:other ;;\n"
            "      missing) echo MANIFEST_UNKNOWN >&2; exit 1 ;;\n"
            "      error) echo registry_unavailable >&2; exit 1 ;;\n"
            "    esac ;;\n"
            "  copy)\n"
            "    printf '%s\\n' \"$2 -> $3\" >> crane-copies\n"
            "    case \"$3\" in *:companion-*) touch companion-copied ;; *) touch lb-copied ;; esac ;;\n"
            "  *) exit 1 ;;\n"
            "esac\n"
        )
        crane.chmod(0o755)

    def test_valid_prerelease_creates_revision_bound_publishers(self):
        environment = self.environment(DRONE_COMMIT_SHA=self.environment()["DRONE_COMMIT_SHA"].upper())
        result = self.run_script(PLANNER, environment=environment)
        self.assertEqual(result.returncode, 0, result)
        self.assertEqual(result.stdout.strip(), "release_plan=ready tag=v1.2.0-alpha.1")
        for kind in ("lb", "companion"):
            guard = self.run_script(GUARD, kind, environment=environment)
            self.assertEqual(guard.returncode, 0, guard)
            self.assertEqual(guard.stdout.strip(), f"release_guard=publish kind={kind}")

    def test_non_tag_events_cannot_plan_or_publish(self):
        for event in ("push", "pull_request"):
            environment = self.environment(DRONE_BUILD_EVENT=event)
            plan = self.run_script(PLANNER, environment=environment)
            self.assertEqual(plan.returncode, 2, plan)
            self.assertEqual(plan.stderr.strip(), "release_plan=error reason=invalid_event")
            guard = self.run_script(GUARD, "lb", environment=environment)
            self.assertEqual(guard.returncode, 2, guard)
            self.assertEqual(guard.stderr.strip(), "release_guard=error reason=invalid_event")

    def test_tag_ref_version_and_head_must_all_match(self):
        cases = (
            ({"DRONE_TAG": "v1.2.0"}, "ref_mismatch"),
            ({"DRONE_COMMIT_REF": "refs/heads/main"}, "ref_mismatch"),
            (
                {
                    "DRONE_TAG": "v1.2.0",
                    "DRONE_COMMIT_REF": "refs/tags/v1.2.0",
                },
                "version_mismatch",
            ),
            ({"DRONE_COMMIT_SHA": "f" * 40}, "head_mismatch"),
            ({"DRONE_COMMIT_SHA": "deadbeef"}, "invalid_revision"),
        )
        for overrides, reason in cases:
            result = self.run_script(PLANNER, environment=self.environment(**overrides))
            self.assertEqual(result.returncode, 2, result)
            self.assertEqual(result.stderr.strip(), f"release_plan=error reason={reason}")

    def test_cargo_build_metadata_is_rejected_as_an_image_tag(self):
        self.write_manifest("1.2.0+build.1")
        self.commit()
        environment = self.environment(
            DRONE_TAG="v1.2.0+build.1",
            DRONE_COMMIT_REF="refs/tags/v1.2.0+build.1",
        )
        result = self.run_script(PLANNER, environment=environment)
        self.assertEqual(result.returncode, 2, result)
        self.assertEqual(result.stderr.strip(), "release_plan=error reason=invalid_image_tag")

    def test_planner_replaces_symlink_without_touching_target(self):
        target = self.root / "attacker"
        target.mkdir()
        (target / "lb").write_text("malicious")
        plan = self.root / ".drone-release-plan"
        plan.symlink_to(target, target_is_directory=True)
        result = self.run_script(PLANNER)
        self.assertEqual(result.returncode, 0, result)
        self.assertFalse(plan.is_symlink())
        self.assertEqual((target / "lb").read_text(), "malicious")
        self.assertTrue((plan / "lb").is_file())

    def test_guard_rejects_missing_stale_and_symlinked_markers(self):
        environment = self.environment()
        missing = self.run_script(GUARD, "lb", environment=environment)
        self.assertEqual(missing.returncode, 2)
        self.assertEqual(missing.stderr.strip(), "release_guard=error reason=invalid_plan")
        plan = self.root / ".drone-release-plan"
        plan.mkdir()
        marker = plan / "lb"
        marker.write_text("stale")
        stale = self.run_script(GUARD, "lb", environment=environment)
        self.assertEqual(stale.returncode, 2)
        self.assertEqual(stale.stderr.strip(), "release_guard=error reason=invalid_marker")
        marker.unlink()
        target = self.root / "marker"
        target.write_text(f"{environment['DRONE_COMMIT_SHA']}\n{environment['DRONE_TAG']}\n")
        marker.symlink_to(target)
        linked = self.run_script(GUARD, "lb", environment=environment)
        self.assertEqual(linked.returncode, 2)
        self.assertEqual(linked.stderr.strip(), "release_guard=error reason=invalid_marker")

    def prepared_publish_environment(self, destination_state):
        environment = self.environment(
            GHCR_USERNAME="fixture",
            GHCR_TOKEN="secret",
            FAKE_DESTINATION_STATE=destination_state,
        )
        plan = self.run_script(PLANNER, environment=environment)
        self.assertEqual(plan.returncode, 0, plan)
        self.install_fake_crane()
        return environment

    def test_registry_publish_copies_only_missing_destinations(self):
        environment = self.prepared_publish_environment("missing")
        sha = environment["DRONE_COMMIT_SHA"]
        for kind in ("lb", "companion"):
            result = self.run_script(PUBLISH, kind, environment=environment)
            self.assertEqual(result.returncode, 0, result)
            self.assertEqual(
                result.stdout.strip(), f"release_publish=complete kind={kind}"
            )
        copies = (self.root / "crane-copies").read_text()
        short = sha[:7]
        self.assertIn(f":rust-{short} -> ghcr.io/helixml/mini-dynamo:v1.2.0-alpha.1", copies)
        self.assertIn(
            f":companion-rust-{short} -> ghcr.io/helixml/mini-dynamo:companion-v1.2.0-alpha.1",
            copies,
        )

    def test_registry_publish_is_idempotent_for_the_same_destination_digest(self):
        environment = self.prepared_publish_environment("same")
        for kind in ("lb", "companion"):
            result = self.run_script(PUBLISH, kind, environment=environment)
            self.assertEqual(result.returncode, 0, result)
            self.assertEqual(
                result.stdout.strip(), f"release_publish=idempotent kind={kind}"
            )
        self.assertFalse((self.root / "crane-copies").exists())

    def test_registry_publish_rejects_a_conflicting_destination_digest(self):
        environment = self.prepared_publish_environment("different")
        result = self.run_script(PUBLISH, "lb", environment=environment)
        self.assertEqual(result.returncode, 2, result)
        self.assertEqual(
            result.stderr.strip(),
            "release_publish=error reason=destination_conflict",
        )
        self.assertFalse((self.root / "crane-copies").exists())

    def test_registry_publish_fails_closed_when_destination_lookup_is_ambiguous(self):
        environment = self.prepared_publish_environment("error")
        result = self.run_script(PUBLISH, "lb", environment=environment)
        self.assertEqual(result.returncode, 2, result)
        self.assertEqual(
            result.stderr.strip(), "release_publish=error reason=destination_lookup"
        )
        self.assertFalse((self.root / "crane-copies").exists())


if __name__ == "__main__":
    unittest.main()
